name: Build apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    name: Build Android APK
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          wget \
          unzip
        pip install --upgrade -r requirements.txt
        pip install --upgrade buildozer cython==0.29.34

    - name: Install Android SDK Build-Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/cmdline-tools
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Build with Buildozer
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        cd build && buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/bin/*.apk
