name: Build apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    name: Build Android APK
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          wget \
          unzip
        pip install --upgrade -r requirements.txt
        pip install --upgrade buildozer cython==0.29.34

    - name: Set up Android SDK
      # Use the pre-built action for a reliable setup
      uses: android-actions/setup-android@v3
      with:
        api-level: 34 # Matches your buildozer.spec file
        build-tools-version: 34.0.0 # Matches your buildozer.spec file
        ndk: 25b # Matches your buildozer.spec file

    - name: Build with Buildozer
      working-directory: ./build
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/bin/*.apk
